[x.common]
mase_type = "placeholder"
mase_op = "placeholder"

[x.software]

[x.hardware]

[seq_0.common]
mase_type = "module"
mase_op = "batch_norm1d"

[seq_0.software]

[seq_0.hardware]

[seq_1.common]
mase_type = "module_related_func"
mase_op = "relu"

[seq_1.software]

[seq_1.hardware]

[seq_2.common]
mase_type = "module_related_func"
mase_op = "linear"

[seq_2.software]

[seq_2.hardware]

[seq_3.common]
mase_type = "module_related_func"
mase_op = "relu"

[seq_3.software]

[seq_3.hardware]

[seq_4.common]
mase_type = "module_related_func"
mase_op = "linear"

[seq_4.software]

[seq_4.hardware]

[seq_5.common]
mase_type = "module_related_func"
mase_op = "relu"

[seq_5.software]

[seq_5.hardware]

[seq_6.common]
mase_type = "module_related_func"
mase_op = "linear"

[seq_6.software]

[seq_6.hardware]

[output.common]
mase_type = "output"
mase_op = "output"

[output.software]

[output.hardware]

[x.common.args]

[output.common.args]

[x.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 16,]
torch_dtype = "torch.float32"

[seq_0.common.args.data_in_0]
shape = [ 8, 16,]
torch_dtype = "torch.float32"
type = "float"
precision = [ 32,]

[seq_0.common.args.weight]
type = "float"
precision = [ 32,]
shape = [ 16,]
from = "NA"

[seq_0.common.args.bias]
type = "float"
precision = [ 32,]
shape = [ 16,]
from = "NA"

[seq_0.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 16,]
torch_dtype = "torch.float32"

[seq_1.common.args.data_in_0]
shape = [ 8, 16,]
torch_dtype = "torch.float32"
type = "float"
precision = [ 32,]

[seq_1.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 16,]
torch_dtype = "torch.float32"

[seq_2.common.args.data_in_0]
shape = [ 8, 16,]
torch_dtype = "torch.float32"
type = "integer"
precision = [ 8, 4,]

[seq_2.common.args.weight]
type = "integer"
precision = [ 8, 4,]
shape = [ 32, 16,]
from = "NA"

[seq_2.common.args.bias]
type = "integer"
precision = [ 8, 4,]
shape = [ 32,]
from = "NA"

[seq_2.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 32,]
torch_dtype = "torch.float32"

[seq_3.common.args.data_in_0]
shape = [ 8, 32,]
torch_dtype = "torch.float32"
type = "float"
precision = [ 32,]

[seq_3.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 32,]
torch_dtype = "torch.float32"

[seq_4.common.args.data_in_0]
shape = [ 8, 32,]
torch_dtype = "torch.float32"
type = "integer"
precision = [ 8, 4,]

[seq_4.common.args.weight]
type = "integer"
precision = [ 8, 4,]
shape = [ 16, 32,]
from = "NA"

[seq_4.common.args.bias]
type = "integer"
precision = [ 8, 4,]
shape = [ 16,]
from = "NA"

[seq_4.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 16,]
torch_dtype = "torch.float32"

[seq_5.common.args.data_in_0]
shape = [ 8, 16,]
torch_dtype = "torch.float32"
type = "float"
precision = [ 32,]

[seq_5.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 16,]
torch_dtype = "torch.float32"

[seq_6.common.args.data_in_0]
shape = [ 8, 16,]
torch_dtype = "torch.float32"
type = "integer"
precision = [ 8, 4,]

[seq_6.common.args.weight]
type = "integer"
precision = [ 8, 4,]
shape = [ 5, 16,]
from = "NA"

[seq_6.common.args.bias]
type = "integer"
precision = [ 8, 4,]
shape = [ 5,]
from = "NA"

[seq_6.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 5,]
torch_dtype = "torch.float32"

[output.common.results.data_out_0]
type = "float"
precision = [ 32,]
shape = [ 8, 5,]
torch_dtype = "torch.float32"
