accelerator: gpu
accumulate_grad_batches: 1
action: train
batch_size: 128
config: null
dataset: jsc
disable_dataset_cache: false
github_ci: false
info: null
is_pretrained: false
is_to_auto_requeue: false
learning_rate: 0.005
load_name: null
load_type: mz
log_every_n_steps: 50
log_level: info
max_epochs: 40
max_steps: -1
max_token_len: 512
model: jsc-m
num_devices: 1
num_nodes: 1
num_targets: 100
num_workers: 16
project: jsc-train-3
project_dir: /home/derek/mase/lab1_output/custom-nn-24-01-25-11-30-58
quant_config: null
report_to: tensorboard
seed: 0
strategy: auto
target: xcu250-figd2104-2L-e
task: classification
to_debug: false
trainer_precision: 16-mixed
training_optimizer: adam
version: null
weight_decay: 0
